[package]
name = "headr"
version = "0.1.0"
edition = "2021"
authors = [ "Hoge Piyo" ]

[dependencies]
anyhow = "1.0.89"
clap = { version = "4.5.18", features = ["derive"] }
pretty_assertions = "1.4.1"

[dev-dependencies]
assert_cmd = "2"
predicates = "2"
pretty_assertions = "1.4.1"
rand = "0.8"
